name: Create GitHub Releases based on changelog
description: GitHub Action for creating GitHub Releases based on changelog

inputs:
  changelog:
    description: Path to changelog
    required: false
  title:
    description: Format of title (variables `$tag`, `$version`, and any string)
    required: false
    default: '$tag'
  draft:
    description: Create a draft release ('0' or '1')
    required: false
    default: '0'

runs:
  using: node12
  main: main.js
